import Head from "next/head";
import Benifits from "../components/Home/Benifits";
import Companies from "../components/Home/Companies";
import Discrib from "../components/Home/Discrib";
import Features from "../components/Home/Features";
import Hero from "../components/Home/Hero";
import JoinUs from "../components/Home/JoinUs";
import Testmonials from "../components/Home/Testmonials";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Feiwoux Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <Companies />
        <Discrib />
        <Benifits />
        <Testmonials />
        <Features />
        <JoinUs />
      </div>
    </div>
  );
}
